/**
 * OpenCode adapter (fork addition).
 *
 * Three sources, merged per scan — the full history is the point, because
 * Desktop's serve API only shows the sessions loaded in the RUNNING Desktop
 * instance (2 at last check) while the real history (25+ sessions across
 * ~10 projects) lives in the session store on the WinPC:
 *
 *   1. Remote session-store snapshot (PRIMARY). The store
 *      (`opencode.db`, the SQLite DB with `session` / `project` /
 *      `workspace` / `session_input` / `part` tables) lives on the WinPC;
 *      the colony pulls a copy over SSH into a local snapshot dir and
 *      queries the copy, never the live file (live-querying over a network
 *      share risks WAL corruption, and a copy never locks Desktop's files).
 *      The pull is mtime-gated — a cheap `ssh` stat runs at most once per
 *      STAT_TTL window, and the ~500MB bulk copy runs only when the remote
 *      signature actually changed, at most once per PULL_MIN window, in the
 *      background so a scan never blocks on a transfer. While Desktop runs,
 *      its `-wal` carries the newest writes, so db AND wal are pulled; the
 *      `-shm` is deliberately NOT copied (shared-memory, rebuilt on open —
 *      a live shm copy is meaningless). The wal stages beside the pending db
 *      under its real `-wal` name, so verification opens the same pair the
 *      swap would publish; a mid-pull Desktop write (fresh re-stat drifts
 *      from the pre-pull signature) or a failed verify discards the set and
 *      the previous snapshot keeps serving.
 *      Config: OPENCODE_DB_SSH_TARGET (falls back to OPENCODE_SSH_TARGET,
 *      the same target the tunnel keeper uses), OPENCODE_DB_REMOTE_PATH
 *      (default `.local/share/opencode/opencode.db`, forward slashes).
 *      Snapshots live under OPENCODE_SNAPSHOT_DIR, else the user cache dir,
 *      else the tmpdir. Threads from here are archive-view-only: the colony
 *      records the archive on its own side; writing a remote store file
 *      from here would race Desktop, which rewrites its records from memory.
 *
 *   2. `opencode serve` HTTP API (LIVE OVERLAY). Desktop binds loopback-only
 *      (127.0.0.1) on a RANDOM port with an AUTOGENERATED password — both
 *      rotate every Desktop launch — so the colony reaches it through a
 *      read-only SSH tunnel, never over the LAN:
 *      `scripts/opencode-tunnel.sh -- <command>` resolves the current port
 *      and credentials fresh on every run (read-only process-env query;
 *      Desktop is never disrupted) and exports OPENCODE_SERVE_URL (plus
 *      OPENCODE_SERVE_USERNAME / OPENCODE_SERVE_PASSWORD). For the live
 *      colony, `scripts/opencode-keeper.sh` (systemd unit template in
 *      scripts/systemd/) holds that tunnel open persistently and publishes
 *      the same three values to a 0600 creds file this adapter reads on
 *      every scan — explicit env always wins, a stale file reads as
 *      unconfigured. A static
 *      OPENCODE_SERVE_URL (or OPENCODE_SERVE_HOST / OPENCODE_SERVE_PORT,
 *      default port 4096) also works for a hand-run LAN-bound serve.
 *      Optional basic auth via OPENCODE_SERVE_USERNAME / OPENCODE_SERVE_PASSWORD.
 *      Endpoints used: GET /session, GET /session/status, GET /project,
 *      GET /session/:id/message?limit=N (previews only, capped per scan).
 *      Serve threads merge INTO the snapshot list by session id: serve fills
 *      in live running flags and any fields the snapshot lacks, and sessions
 *      the snapshot has not seen yet (too new to have pulled) appear
 *      serve-backed until the next snapshot refresh absorbs them.
 *
 *   3. Local session-store copy (UNION MEMBER). Same copy-then-query
 *      mechanics as before for a store on THIS machine: the copy refreshes
 *      only when the source mtime/size changes (mtime cache, per ground
 *      rules). Point at one with OPENCODE_DB_PATH — e.g. a file pulled from
 *      the WinPC by hand — or leave unset for this machine's default store.
 *      This is how the host's own sessions (if any) still show alongside
 *      the WinPC history.
 *
 * Archive flag is the store's own `session.time_archived` (null = active),
 * set with one atomic UPDATE after re-reading the row — the colony never
 * invents its own archive state. That write only ever touches a LOCAL store
 * file we resolved ourselves (never a snapshot copy, never a remote pull):
 * snapshot-backed threads are view-only for archiving, and the serve API
 * has no archive endpoint (only title PATCH), so serve-sourced threads are
 * view-only too.
 *
 * Opening: a thread opens iff it has a `share_url` — there is no Desktop deep
 * link to hand back, so unshared threads report why per the interface.
 *
 * Times in the store are epoch milliseconds (verified against a live db).
 */

import { spawn, spawnSync } from 'node:child_process'
import { DatabaseSync } from 'node:sqlite'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import {
  maxSeenIso,
  noteRemoteSeen,
  remoteHostLabel,
  remoteSeenIso,
  withRemoteTopology,
} from './remote-stat.mjs'

/* ---------------------------------------------------------------- config */

const numEnv = (name, fallback) => {
  const v = Number(process.env[name])
  return Number.isFinite(v) && v > 0 ? v : fallback
}

/** Base URL of `opencode serve`, or '' when the serve path is unconfigured. */
function serveBase() {
  const url = (process.env.OPENCODE_SERVE_URL || '').trim().replace(/\/+$/, '')
  if (url) return url
  const fileUrl = (readServeCreds().OPENCODE_SERVE_URL || '').trim().replace(/\/+$/, '')
  if (fileUrl) return fileUrl
  const host = (process.env.OPENCODE_SERVE_HOST || '').trim()
  if (!host) return ''
  const port = (process.env.OPENCODE_SERVE_PORT || '4096').trim()
  const withScheme = /^https?:\/\//i.test(host) ? host : `http://${host}`
  return `${withScheme.replace(/\/+$/, '')}:${port}`
}

/* --------------------------------------- keeper-published creds file */

/**
 * Where scripts/opencode-keeper.sh publishes the live serve URL + rotated
 * credentials (0600, rewritten on every healthy probe). Explicit env config
 * always wins; the file is only a fallback so a Desktop restart (random port
 * and autogenerated password both rotate) needs no colony restart. A stale
 * file — the keeper removes it when the serve path is down, this TTL is the
 * backstop for a dead keeper — reads as unconfigured, so scans skip the
 * serve path instead of stalling on timeouts.
 */
const CREDS_TTL_MS = 3 * 60 * 1000

function credsFilePath() {
  const explicit = (process.env.OPENCODE_SERVE_CREDS_FILE || '').trim()
  if (explicit) return explicit
  const runtime = (process.env.XDG_RUNTIME_DIR || '').trim()
  const dir = runtime || os.tmpdir()
  return path.join(dir, 'bot-crossing', 'opencode-serve.env')
}

let credsCache = { key: '', creds: {} }

/** Shell-style KEY=value lines (one layer of matching quotes stripped). */
function readServeCreds() {
  const file = credsFilePath()
  let stat
  try {
    stat = fs.statSync(file)
  } catch {
    return {}
  }
  const key = `${file} ${stat.mtimeMs}`
  if (credsCache.key === key) return credsCache.creds
  const creds = {}
  try {
    for (const line of fs.readFileSync(file, 'utf8').split('\n')) {
      const m = line.match(/^(OPENCODE_SERVE_(URL|USERNAME|PASSWORD|UPDATED_AT))=(.*)$/)
      if (!m) continue
      let value = m[3].trim()
      if (value.length >= 2 && value.startsWith("'") && value.endsWith("'")) {
        value = value.slice(1, -1)
      }
      creds[m[1]] = value
    }
  } catch {
    return {}
  }
  const updated = Number(creds.OPENCODE_SERVE_UPDATED_AT) || stat.mtimeMs
  if (!Number.isFinite(updated) || Date.now() - updated > CREDS_TTL_MS) return {}
  credsCache = { key, creds }
  return creds
}

function serveHeaders() {
  const fileCreds = readServeCreds()
  const password = process.env.OPENCODE_SERVE_PASSWORD || fileCreds.OPENCODE_SERVE_PASSWORD
  if (!password) return {}
  const user = process.env.OPENCODE_SERVE_USERNAME || fileCreds.OPENCODE_SERVE_USERNAME || 'opencode'
  return { authorization: `Basic ${Buffer.from(`${user}:${password}`).toString('base64')}` }
}

/** Candidate homes: the sandbox-proof real home first, then the usual ones. */
function homeCandidates() {
  const homes = [process.env.HERMES_REAL_HOME, process.env.HOME, os.homedir()].filter(Boolean)
  return [...new Set(homes)]
}

/* ------------------------------------------------------- snapshot layout */

/**
 * Persistent cache first: a ~500MB snapshot must survive colony restarts and
 * host reboots, or every restart pays a full re-pull. Tmpdir is the last
 * resort, not the default.
 */
function snapshotDir() {
  const explicit = (process.env.OPENCODE_SNAPSHOT_DIR || '').trim()
  if (explicit) return explicit
  const cache = (process.env.XDG_CACHE_HOME || '').trim()
  if (cache) return path.join(cache, 'bot-crossing', 'opencode')
  for (const h of homeCandidates()) {
    if (h) return path.join(h, '.cache', 'bot-crossing', 'opencode')
  }
  return path.join(os.tmpdir(), 'bot-crossing-opencode')
}

const SNAP_DIR = snapshotDir()
/** Local-source copy (explicit OPENCODE_DB_PATH or this machine's store). */
const LOCAL_SNAPSHOT_DB = path.join(SNAP_DIR, 'local-opencode.db')
/** WinPC pull: db + wal + meta live here; -shm is never copied. */
const REMOTE_SNAPSHOT_DB = path.join(SNAP_DIR, 'remote-opencode.db')
const REMOTE_META_FILE = path.join(SNAP_DIR, 'remote-opencode.json')

/** Where the session store might live on this machine (never touched live). */
function dbCandidates() {
  const out = []
  if (process.env.OPENCODE_DB_PATH) out.push(process.env.OPENCODE_DB_PATH)
  for (const h of homeCandidates()) out.push(path.join(h, '.local', 'share', 'opencode', 'opencode.db'))
  return out
}

function resolveSourceDB() {
  for (const file of dbCandidates()) {
    try {
      if (file && fs.statSync(file).isFile()) return file
    } catch {
      /* missing — next candidate */
    }
  }
  return ''
}

/** True when the file is one of our own snapshot copies (never the store). */
function isSnapshotCopy(file) {
  try {
    const real = fs.realpathSync(file)
    for (const snap of [LOCAL_SNAPSHOT_DB, REMOTE_SNAPSHOT_DB]) {
      try {
        if (real === fs.realpathSync(snap)) return true
      } catch {
        if (real === snap) return true
      }
    }
  } catch {
    /* source does not exist (yet) — not a copy we manage */
  }
  return false
}

/* ------------------------------------------------------- throttled warns */

/**
 * The UI polls /api/threads every few seconds; an unreachable WinPC must not
 * spam the journal on every poll. One line per key per minute is enough.
 */
const lastWarnAt = new Map()
function warnThrottled(key, msg) {
  const now = Date.now()
  if (now - (lastWarnAt.get(key) || 0) < 60 * 1000) return
  lastWarnAt.set(key, now)
  console.warn(`bot-crossing: opencode ${msg}`)
}

/* ------------------------------------------------- remote snapshot pull */

/**
 * The WinPC session store, pulled over SSH. Target reuses the tunnel
 * keeper's OPENCODE_SSH_TARGET unless OPENCODE_DB_SSH_TARGET overrides it,
 * so disabling the pull is one unset — and no machine names, LAN IPs, or
 * SSH usernames ever land in the repo.
 */
function remoteConfig() {
  const target = (process.env.OPENCODE_DB_SSH_TARGET || process.env.OPENCODE_SSH_TARGET || '').trim()
  if (!target) return null
  if (!/^[^@\s]+@[^@\s:]+$/.test(target)) {
    warnThrottled('target', `ignoring malformed snapshot SSH target (${target.length} chars)`)
    return null
  }
  const remotePath = (process.env.OPENCODE_DB_REMOTE_PATH || '.local/share/opencode/opencode.db').trim()
  if (!/^[A-Za-z0-9._\/\\:-]+$/.test(remotePath) || remotePath.includes('..')) {
    warnThrottled('path', 'ignoring unsafe OPENCODE_DB_REMOTE_PATH')
    return null
  }
  return { target, remotePath }
}

/**
 * Cheap remote signature: sizes + write ticks of db and wal. PowerShell
 * startup dominates (~1-2s), so the result is cached for STAT_TTL — and a
 * failed stat (WinPC/Desktop down) caches as unreachable for the same
 * window, so one slow scan per minute is the worst case, not one per poll.
 */
function statTTLMs() {
  return numEnv('OPENCODE_DB_STAT_TTL_SECONDS', 60) * 1000
}

let statCache = { at: 0, sig: '', ok: false }

/**
 * Colony-host stamp of the last successful remote contact (stat success or
 * fresh pull). Survives failed scans so unreachable threads keep a stale
 * lastSeenAt instead of losing it; the persisted pull time covers restarts.
 */
let lastRemoteSeenAt = 0

const remoteHost = () => remoteHostLabel(['OPENCODE_REMOTE_HOST_LABEL', 'REMOTE_HOST_LABEL'])

function remoteTopology() {
  let metaAt = 0
  try {
    const meta = readRemoteMeta()
    if (meta && Number.isFinite(Number(meta.pulledAt))) metaAt = Number(meta.pulledAt)
  } catch {
    /* no meta yet — stamp stays memory-only */
  }
  return { host: remoteHost(), lastSeenAt: remoteSeenIso(statCache, lastRemoteSeenAt, metaAt) }
}

function remoteStat(cfg, force = false) {
  const now = Date.now()
  if (!force && now - statCache.at < statTTLMs() && statCache.sig !== '') return statCache
  const rel = cfg.remotePath.replace(/\//g, '\\')
  const ps =
    `$rel='${rel}';` +
    `$p=Join-Path $env:USERPROFILE $rel;` +
    `$d=Get-Item -LiteralPath $p -ErrorAction SilentlyContinue;` +
    `if ($d) { Write-Output ('SIZE=' + $d.Length); Write-Output ('MTIME=' + $d.LastWriteTimeUtc.Ticks) }` +
    `$w=Get-Item -LiteralPath ($p + '-wal') -ErrorAction SilentlyContinue;` +
    `if ($w) { Write-Output ('WALSIZE=' + $w.Length); Write-Output ('WALMTIME=' + $w.LastWriteTimeUtc.Ticks) }`
  let sig = ''
  let ok = false
  try {
    const out = spawnSync('ssh',
      ['-o', 'BatchMode=yes', '-o', 'ConnectTimeout=10', cfg.target,
        'powershell -NoProfile -Command -'],
      { input: ps, encoding: 'utf8', timeout: 25000, windowsHide: true })
    if (out.status === 0 && out.stdout) {
      const vals = {}
      for (const line of String(out.stdout).split('\n')) {
        const m = line.replace(/\r/g, '').match(/^(SIZE|MTIME|WALSIZE|WALMTIME)=(\d+)$/)
        if (m) vals[m[1]] = m[2]
      }
      if (vals.SIZE) {
        sig = `${vals.SIZE}:${vals.MTIME || 0}|${vals.WALSIZE || 0}:${vals.WALMTIME || 0}`
        ok = true
      }
    }
  } catch {
    ok = false
  }
  // Cache negatives too (sig '' + ok false still records `at`): an
  // unreachable WinPC costs one slow scan per STAT_TTL, not one per poll.
  statCache = { at: now, sig: ok ? sig : statCache.sig, ok }
  if (ok) lastRemoteSeenAt = noteRemoteSeen(statCache, lastRemoteSeenAt)
  return statCache
}

function readRemoteMeta() {
  try {
    const raw = JSON.parse(fs.readFileSync(REMOTE_META_FILE, 'utf8'))
    if (raw && typeof raw === 'object' && typeof raw.sig === 'string') return raw
  } catch {
    /* no meta yet — first pull */
  }
  return null
}

function remoteSnapshotReady(meta, sig) {
  if (!meta || meta.sig !== sig) return false
  try {
    return fs.statSync(REMOTE_SNAPSHOT_DB).isFile()
  } catch {
    return false
  }
}

/** Minimum gap between bulk pulls — the wal ticks on every Desktop write. */
function pullMinMs() {
  return numEnv('OPENCODE_DB_PULL_MIN_SECONDS', 180) * 1000
}

let pullInFlight = false
let lastPullAttempt = 0

/**
 * Verify a pulled copy before it goes live: the pending db stages with its
 * wal under the real `-wal` name, so this opens the same pair the swap
 * would publish (deletes included). Only `-shm`/`-journal` are dropped
 * afterwards — both are read sidecars SQLite rebuilds; the `-wal` is pulled
 * data and must survive verification.
 */
function verifySnapshot(file) {
  let db
  try {
    db = new DatabaseSync(file, { readOnly: true })
    const tables = new Set(
      db.prepare("SELECT name FROM sqlite_master WHERE type='table'").all().map((r) => r.name))
    if (!tables.has('session')) return { ok: false, error: 'no session table' }
    const row = db.prepare('SELECT COUNT(*) AS n FROM session').get()
    return { ok: true, sessions: Number(row && row.n) || 0 }
  } catch (err) {
    return { ok: false, error: String((err && err.message) || err) }
  } finally {
    try {
      db && db.close()
    } catch {
      /* already gone */
    }
    for (const suffix of ['-shm', '-journal']) {
      try {
        fs.rmSync(file + suffix, { force: true })
      } catch {
        /* already gone */
      }
    }
  }
}

function finishPull(cfg, sig, nextDb, nextWal, startedAt) {
  pullInFlight = false
  // Torn-pair guard: the db (~500MB) and wal copies are sequential, so a
  // Desktop write mid-pull pairs a newer wal with an older db. Re-stat
  // fresh (bypassing the TTL cache); any signature drift discards the set
  // and the previous snapshot keeps serving until the next window retries.
  let fresh = { ok: false, sig: '' }
  try {
    fresh = remoteStat(cfg, true)
  } catch {
    /* unreachable — discarded below */
  }
  if (!fresh.ok || fresh.sig !== sig) {
    for (const f of [nextDb, nextWal]) {
      try {
        fs.rmSync(f, { force: true })
      } catch {
        /* best effort */
      }
    }
    warnThrottled('pull-torn', 'snapshot pull raced a Desktop write — keeping previous snapshot')
    return
  }
  const check = verifySnapshot(nextDb)
  // Drop verify sidecars; a missing wal pull is fine (nextWal simply absent).
  for (const f of [nextDb + '-shm', nextDb + '-journal']) {
    try {
      fs.rmSync(f, { force: true })
    } catch {
      /* best effort */
    }
  }
  if (!check.ok) {
    for (const f of [nextDb, nextWal]) {
      try {
        fs.rmSync(f, { force: true })
      } catch {
        /* best effort */
      }
    }
    warnThrottled('pull-verify', `snapshot pull failed verification (${check.error}) — keeping previous snapshot`)
    return
  }
  try {
    fs.mkdirSync(SNAP_DIR, { recursive: true })
    // Drop the live wal first: a new db without its wal is the last
    // checkpointed (consistent, slightly stale) view; the new wal replays
    // on top of it. The reverse order (new wal + old db) can refuse to open.
    for (const suffix of ['-wal', '-shm', '-journal']) {
      try {
        fs.rmSync(REMOTE_SNAPSHOT_DB + suffix, { force: true })
      } catch {
        /* already gone */
      }
    }
    fs.renameSync(nextDb, REMOTE_SNAPSHOT_DB)
    try {
      if (fs.statSync(nextWal).isFile()) fs.renameSync(nextWal, REMOTE_SNAPSHOT_DB + '-wal')
    } catch {
      /* fully checkpointed — the db file alone is a consistent view */
    }
    let walBytes = 0
    try {
      const wst = fs.statSync(REMOTE_SNAPSHOT_DB + '-wal')
      if (wst.isFile()) walBytes = wst.size
    } catch {
      /* no wal live — db alone is the consistent view */
    }
    fs.writeFileSync(REMOTE_META_FILE, JSON.stringify({
      sig,
      pulledAt: Date.now(),
      pullSeconds: Math.round((Date.now() - startedAt) / 1000),
      sessions: check.sessions,
      walBytes,
      target: cfg.target.split('@')[1] || '',
    }))
    lastRemoteSeenAt = Date.now()
    console.warn(`bot-crossing: opencode snapshot refreshed (${check.sessions} sessions)`)
  } catch (err) {
    warnThrottled('pull-swap', `snapshot pull could not go live (${err.message}) — keeping previous snapshot`)
  }
}

/**
 * Start a background `scp` of db + wal. Never blocks the scan: the previous
 * snapshot (or serve-only, on first run) keeps serving until the new copy
 * verifies and swaps in.
 */
function startBackgroundPull(cfg, sig) {
  if (pullInFlight) return
  const now = Date.now()
  if (now - lastPullAttempt < pullMinMs()) return
  lastPullAttempt = now
  pullInFlight = true
  let started
  try {
    fs.mkdirSync(SNAP_DIR, { recursive: true })
    const nextDb = REMOTE_SNAPSHOT_DB + '.next'
    const nextWal = REMOTE_SNAPSHOT_DB + '.next-wal'
    for (const f of [nextDb, nextWal]) {
      try {
        fs.rmSync(f, { force: true })
      } catch {
        /* already gone */
      }
    }
    started = spawn('scp',
      ['-o', 'BatchMode=yes', '-o', 'ConnectTimeout=15',
        `${cfg.target}:${cfg.remotePath}`, nextDb],
      { stdio: 'ignore', windowsHide: true })
  } catch (err) {
    pullInFlight = false
    warnThrottled('pull-spawn', `snapshot pull could not start (${err.message})`)
    return
  }
  const startedAt = Date.now()
  const nextDb = REMOTE_SNAPSHOT_DB + '.next'
  const nextWal = REMOTE_SNAPSHOT_DB + '.next-wal'
  started.on('error', () => {
    pullInFlight = false
  })
  started.on('close', (code) => {
    if (code !== 0) {
      pullInFlight = false
      try {
        fs.rmSync(nextDb, { force: true })
      } catch {
        /* best effort */
      }
      warnThrottled('pull-scp', 'snapshot db pull failed (Desktop mid-write or WinPC busy) — keeping previous snapshot')
      return
    }
    // Wal second, best effort: without it the db is the last checkpoint.
    const wal = spawn('scp',
      ['-o', 'BatchMode=yes', '-o', 'ConnectTimeout=15',
        `${cfg.target}:${cfg.remotePath}-wal`, nextWal],
      { stdio: 'ignore', windowsHide: true })
    wal.on('error', () => finishPull(cfg, sig, nextDb, nextWal, startedAt))
    wal.on('close', () => finishPull(cfg, sig, nextDb, nextWal, startedAt))
  })
}

/**
 * Local path of the remote snapshot, or '' when there is nothing usable.
 * Kicks off a background refresh when stale — the scan uses whatever is on
 * disk meanwhile, so killing Desktop/WinPC degrades to the last snapshot
 * instead of breaking the scan.
 */
function ensureRemoteSnapshot() {
  const cfg = remoteConfig()
  if (!cfg) return ''
  let stat
  try {
    stat = remoteStat(cfg)
  } catch {
    stat = { ok: false, sig: '' }
  }
  const meta = readRemoteMeta()
  if (stat.ok && stat.sig) {
    if (remoteSnapshotReady(meta, stat.sig)) return REMOTE_SNAPSHOT_DB
    startBackgroundPull(cfg, stat.sig)
    // Stale-but-present snapshot still serves while the refresh flies.
    try {
      if (fs.statSync(REMOTE_SNAPSHOT_DB).isFile()) return REMOTE_SNAPSHOT_DB
    } catch {
      /* first pull still running — serve-only this scan */
    }
    return ''
  }
  // Remote unreachable: last snapshot stands in, whatever its age.
  if (meta) {
    try {
      if (fs.statSync(REMOTE_SNAPSHOT_DB).isFile()) return REMOTE_SNAPSHOT_DB
    } catch {
      /* snapshot vanished — nothing to serve */
    }
  }
  return ''
}

async function detect() {
  if (serveBase()) return true
  if (remoteConfig()) return true
  return resolveSourceDB() !== ''
}

/* ------------------------------------------------------------ serve path */

const SERVE_TIMEOUT_MS = 4000
/** Previews cost one HTTP call per session — cap them; oldest threads go without. */
const SERVE_PREVIEW_SESSIONS = 30
const SERVE_PREVIEW_LIMIT = 20

async function serveGet(base, route) {
  const res = await fetch(`${base}${route}`, {
    headers: { accept: 'application/json', ...serveHeaders() },
    signal: AbortSignal.timeout(SERVE_TIMEOUT_MS),
  })
  if (!res.ok) throw new Error(`opencode serve ${route} -> HTTP ${res.status}`)
  return res.json()
}

const asArray = (v) => (Array.isArray(v) ? v : [])
const str = (v) => (typeof v === 'string' ? v : v == null ? '' : String(v))
const num = (v) => (typeof v === 'number' && Number.isFinite(v) ? v : 0)

/**
 * The store's `model` column is a plain id on some builds and a JSON blob
 * (`{"id":...,"providerID":...}`) on Desktop 1.18.x — show the id either way.
 */
function modelName(v) {
  if (v && typeof v === 'object') return str(v.modelID ?? v.model_id ?? v.id)
  const s = str(v)
  if (s.startsWith('{')) {
    try {
      const o = JSON.parse(s)
      if (o && typeof o === 'object') return str(o.id || o.modelID || o.model_id)
    } catch {
      /* not JSON after all — fall through to the raw string */
    }
  }
  return s
}

/** First user prompt out of a serve message list [{info:{role},parts:[{type,text}]}]. */
function servePreview(messages) {
  for (const m of asArray(messages)) {
    if (!m || typeof m !== 'object') continue
    if (str(m.info && m.info.role).toLowerCase() !== 'user') continue
    for (const p of asArray(m.parts)) {
      if (p && typeof p === 'object' && p.type === 'text' && str(p.text).trim()) {
        return str(p.text).trim().slice(0, 280)
      }
    }
  }
  return ''
}

function serveThread(s, projects, statuses) {
  const time = (s && typeof s === 'object' && typeof s.time === 'object' && s.time) || {}
  const createdAt = num(s.time_created ?? time.created)
  const lastActivityAt = num(s.time_updated ?? time.updated ?? createdAt)
  const id = str(s.id)
  const projectID = str(s.projectID ?? s.project_id)
  const project = projects.get(projectID)
  const directory = str(s.directory)
  const projectPath = (project && project.worktree && project.worktree !== '/'
    ? str(project.worktree)
    : str(project && project.directory)) || directory
  const status = statuses.get(id)
  const running = status === 'running'
    || (status && typeof status === 'object' && (status.type === 'running' || status.running === true))
    || Date.now() - lastActivityAt < RECENT_WINDOW_MS
  const shareUrl = str(s.share_url ?? s.shareUrl)
  return {
    id: `opencode:${id}`,
    title: str(s.title) || 'Untitled thread',
    preview: '',
    project: (project && project.name) || (projectPath ? path.basename(projectPath) : '') || 'unknown',
    projectPath,
    worktree: '',
    cwd: directory,
    gitBranch: str((project && project.branch) ?? s.branch),
    model: modelName(s.modelID ?? s.model_id ?? (s.model && s.model.modelID) ?? s.model),
    effort: '',
    createdAt,
    lastActivityAt,
    lastFocusedAt: 0,
    running,
    unread: false,
    hasError: false,
    archived: false,
    sizeBytes: 500,
    source: 'serve',
    canOpen: Boolean(shareUrl),
    ref: { sessionId: id, via: 'serve', shareUrl },
  }
}

async function scanViaServe() {
  const base = serveBase()
  const sessions = asArray(await serveGet(base, '/session'))
  let statuses = new Map()
  try {
    const raw = await serveGet(base, '/session/status')
    if (raw && typeof raw === 'object') statuses = new Map(Object.entries(raw))
  } catch {
    /* status is best-effort; recency fills in below */
  }
  let projects = new Map()
  try {
    for (const p of asArray(await serveGet(base, '/project'))) {
      if (p && typeof p === 'object' && p.id) {
        projects.set(str(p.id), {
          name: str(p.name),
          worktree: str(p.worktree),
          directory: str(p.directory),
          branch: str(p.branch),
        })
      }
    }
  } catch {
    /* names fall back to the session directory basename */
  }
  const ordered = sessions
    .filter((s) => s && typeof s === 'object' && s.id)
    .sort((a, b) => num((b.time && b.time.updated) ?? b.time_updated) - num((a.time && a.time.updated) ?? a.time_updated))
  const threads = ordered.map((s) => serveThread(s, projects, statuses))
  // Previews, newest first, bounded concurrency so one slow session
  // cannot hold the scan hostage.
  const ids = threads.slice(0, SERVE_PREVIEW_SESSIONS)
  const queue = ids.map((t, i) => [t, ordered[i]])
  await Promise.all(Array.from({ length: 6 }, async () => {
    while (queue.length) {
      const [t, s] = queue.pop()
      try {
        const messages = asArray(await serveGet(base, `/session/${encodeURIComponent(s.id)}/message?limit=${SERVE_PREVIEW_LIMIT}`))
        t.preview = servePreview(messages)
      } catch {
        /* preview stays '' — the thread still stands on the map */
      }
    }
  }))
  // Serve is the live overlay path: every thread here is remote. One
  // topology computation per scan, not per thread (meta is a file read).
  const topology = remoteTopology()
  return threads.map((t) => withRemoteTopology(t, topology))
}

/* --------------------------------------------------------------- db path */

/** Updated within this window counts as working right now (db path only). */
const RECENT_WINDOW_MS = 5 * 60 * 1000

let snapshotCache = { key: '', source: '', snap: '' }

/** stat signature (db + wal) — the copy refreshes only when this changes. */
function sourceKey(source) {
  const sig = (f) => {
    try {
      const st = fs.statSync(f)
      return `${st.mtimeMs}:${st.size}`
    } catch {
      return '-'
    }
  }
  return `${sig(source)}|${sig(source + '-wal')}`
}

/**
 * Copy the store to a tmp snapshot, never opening the source itself —
 * the source may sit on a network share where live SQLite access risks
 * WAL corruption, and locally a copy never locks the harness's files.
 */
function snapshotDB(source) {
  const key = sourceKey(source)
  if (snapshotCache.key === key && snapshotCache.source === source && snapshotCache.snap) {
    try {
      if (fs.statSync(snapshotCache.snap).isFile()) return snapshotCache.snap
    } catch {
      /* snapshot vanished — fall through and re-copy */
    }
  }
  // Same-file guard: the source already IS a snapshot we manage.
  if (isSnapshotCopy(source)) {
    snapshotCache = { key, source, snap: source }
    return source
  }
  fs.mkdirSync(SNAP_DIR, { recursive: true })
  // Remove a stale wal/shm first: a previous snapshot's wal must never
  // shadow a source that has since checkpointed.
  for (const suffix of ['-wal', '-shm', '-journal']) {
    try {
      fs.rmSync(LOCAL_SNAPSHOT_DB + suffix, { force: true })
    } catch {
      /* already gone */
    }
  }
  fs.copyFileSync(source, LOCAL_SNAPSHOT_DB)
  try {
    fs.copyFileSync(source + '-wal', LOCAL_SNAPSHOT_DB + '-wal')
  } catch {
    /* fully checkpointed — the db file alone is a consistent view */
  }
  snapshotCache = { key, source, snap: LOCAL_SNAPSHOT_DB }
  return LOCAL_SNAPSHOT_DB
}

const openRead = (file) => new DatabaseSync(file, { readOnly: true })

function tableNames(db) {
  try {
    return new Set(db.prepare("SELECT name FROM sqlite_master WHERE type='table'").all().map((r) => r.name))
  } catch {
    return new Set()
  }
}

/** First user prompt from the message/part tables (fallback when session_input is absent). */
function partsPreview(db, tables, sessionId) {
  if (!tables.has('part') || !tables.has('message')) return ''
  let rows = []
  try {
    rows = db.prepare(
      `SELECT p.data AS pdata, m.data AS mdata FROM part p
         JOIN message m ON m.id = p.message_id
        WHERE p.session_id = ? ORDER BY p.time_created ASC LIMIT 25`
    ).all(sessionId)
  } catch {
    return ''
  }
  for (const row of rows) {
    let msg = null
    let part = null
    try {
      msg = JSON.parse(row.mdata)
    } catch {
      continue
    }
    if (!msg || typeof msg !== 'object' || str(msg.role).toLowerCase() !== 'user') continue
    try {
      part = JSON.parse(row.pdata)
    } catch {
      continue
    }
    if (part && typeof part === 'object' && part.type === 'text' && str(part.text).trim()) {
      return str(part.text).trim().slice(0, 280)
    }
  }
  return ''
}

const THREAD_SQL = `
  SELECT s.id, s.project_id, s.workspace_id, s.directory, s.title, s.agent, s.model,
         s.cost, s.tokens_input, s.tokens_output, s.tokens_reasoning,
         s.share_url, s.time_created, s.time_updated, s.time_archived,
         p.name AS project_name,
         w.branch AS ws_branch,
         (SELECT pd.directory FROM project_directory pd
           WHERE pd.project_id = s.project_id LIMIT 1) AS project_dir,
         __FIRST_PROMPT__ AS first_prompt
    FROM session s
    LEFT JOIN project p ON p.id = s.project_id
    LEFT JOIN workspace w ON w.id = s.workspace_id
   ORDER BY s.time_updated DESC
`

/**
 * Which column holds the directory list changed across OpenCode releases
 * (`project.directory` vs the `project_directory` join table) — probe once
 * per snapshot rather than assuming.
 */
function directorySubselect(db, tables) {
  if (tables.has('project_directory')) {
    try {
      db.prepare('SELECT directory FROM project_directory LIMIT 1').get()
      return `(SELECT pd.directory FROM project_directory pd
           WHERE pd.project_id = s.project_id LIMIT 1)`
    } catch {
      /* table exists but shape differs — fall through */
    }
  }
  if (tables.has('project')) {
    try {
      const cols = db.prepare('PRAGMA table_info(project)').all().map((r) => r.name)
      if (cols.includes('directory')) return `(SELECT p2.directory FROM project p2 WHERE p2.id = s.project_id LIMIT 1)`
    } catch {
      /* fall through to no directory */
    }
  }
  return `NULL`
}

function toThread(row, preview, via) {
  const projectPath = str(row.project_dir) || str(row.directory)
  const tokens = num(row.tokens_input) + num(row.tokens_output) + num(row.tokens_reasoning)
  const lastActivityAt = num(row.time_updated) || num(row.time_created)
  const shareUrl = str(row.share_url)
  const remote = via === 'db-remote'
  return {
    id: `opencode:${row.id}`,
    title: str(row.title) || 'Untitled thread',
    preview,
    project: str(row.project_name) || (projectPath ? path.basename(projectPath) : '') || 'unknown',
    projectPath,
    worktree: '',
    cwd: str(row.directory),
    gitBranch: str(row.ws_branch),
    model: modelName(row.model),
    effort: '',
    createdAt: num(row.time_created),
    lastActivityAt,
    lastFocusedAt: 0,
    running: Date.now() - lastActivityAt < RECENT_WINDOW_MS,
    unread: false,
    hasError: false,
    archived: row.time_archived != null,
    sizeBytes: tokens > 0 ? tokens * 4 : 500,
    source: remote ? 'db-remote' : 'db',
    canOpen: Boolean(shareUrl),
    ref: { sessionId: str(row.id), via, shareUrl },
  }
}

function scanSnapshotFile(snap, via) {
  const db = openRead(snap)
  try {
    const tables = tableNames(db)
    if (!tables.has('session')) throw new Error('opencode snapshot has no session table')
    const hasInput = tables.has('session_input')
    const sql = THREAD_SQL
      .replace(
        '__FIRST_PROMPT__',
        hasInput
          ? `(SELECT si.prompt FROM session_input si
              WHERE si.session_id = s.id ORDER BY si.time_created ASC LIMIT 1)`
          : `NULL`
      )
      .replace(
        `(SELECT pd.directory FROM project_directory pd
           WHERE pd.project_id = s.project_id LIMIT 1)`,
        directorySubselect(db, tables)
      )
    let rows = []
    try {
      rows = db.prepare(sql).all()
    } catch (err) {
      throw new Error(`opencode session query failed: ${err.message}`)
    }
    return rows.map((row) => {
      let preview = str(row.first_prompt).trim().slice(0, 280)
      // Skip this record's parts lookup only when the prompt already speaks.
      if (!preview) {
        try {
          preview = partsPreview(db, tables, row.id)
        } catch {
          preview = ''
        }
      }
      return toThread(row, preview, via)
    })
  } finally {
    db.close()
  }
}

/** Every db-backed thread: remote snapshot first, then local sources. */
function scanViaDB() {
  const out = []
  const seen = new Set()
  const take = (threads) => {
    for (const t of threads) {
      if (seen.has(t.id)) continue
      seen.add(t.id)
      out.push(t)
    }
  }
  const remoteSnap = ensureRemoteSnapshot()
  if (remoteSnap) {
    try {
      const topology = remoteTopology()
      take(scanSnapshotFile(remoteSnap, 'db-remote').map((t) => withRemoteTopology(t, topology)))
    } catch (err) {
      warnThrottled('remote-scan', `remote snapshot unreadable (${err.message}) — keeping previous on next pull`)
    }
  }
  const source = resolveSourceDB()
  if (source && !isSnapshotCopy(source)) {
    try {
      take(scanSnapshotFile(snapshotDB(source), 'db'))
    } catch (err) {
      warnThrottled('local-scan', `local store unreadable (${err.message})`)
    }
  }
  if (!out.length) {
    if (!remoteConfig() && !source) {
      throw new Error('No OpenCode session store found (set OPENCODE_DB_PATH or OPENCODE_SERVE_URL)')
    }
    throw new Error('No OpenCode session store readable right now')
  }
  return out
}

/* ---------------------------------------------------------- merge + scan */

const bareId = (threadId) => str(threadId).replace(/^opencode:/, '')

/**
 * Serve is the live overlay on a snapshot base: liveness wins, and any
 * field the snapshot lacks (share granted after the pull, a title set in
 * Desktop, a model the old row never recorded) fills in. Identity,
 * archive state, and the ref stay snapshot-backed.
 */
function overlayServe(base, live) {
  const pick = (a, b) => (str(a) && a !== 'Untitled thread' ? a : str(b) || a)
  const liveShare = live.ref && typeof live.ref.shareUrl === 'string' ? live.ref.shareUrl.trim() : ''
  const baseShare = base.ref && typeof base.ref.shareUrl === 'string' ? base.ref.shareUrl.trim() : ''
  const shareUrl = baseShare || liveShare
  const merged = {
    ...base,
    title: pick(base.title, live.title),
    preview: base.preview || live.preview,
    project: base.project === 'unknown' && live.project ? live.project : base.project,
    projectPath: base.projectPath || live.projectPath,
    cwd: base.cwd || live.cwd,
    gitBranch: base.gitBranch || live.gitBranch,
    model: base.model || live.model,
    lastActivityAt: Math.max(base.lastActivityAt, live.lastActivityAt),
    running: base.running || live.running,
    canOpen: Boolean(shareUrl) || base.canOpen,
    ref: { ...base.ref, shareUrl },
  }
  // Topology follows the base: a snapshot-backed remote thread stays remote
  // with the later stamp; a local base stays local (no fields added).
  if (base && base.remote === true) {
    merged.host = base.host || live.host || remoteHost()
    merged.remote = true
    const seen = maxSeenIso(base.lastSeenAt, live.lastSeenAt)
    if (seen) merged.lastSeenAt = seen
    else delete merged.lastSeenAt
  }
  return merged
}

async function scanServeSafe() {
  if (!serveBase()) return []
  try {
    return await scanViaServe()
  } catch (err) {
    // Serve is the overlay, never the gate: fall back to the snapshot.
    warnThrottled('serve', `serve unreachable (${err.message}) — snapshot stands in`)
    return []
  }
}

function scanDBSafe() {
  try {
    return scanViaDB()
  } catch (err) {
    // No db source at all is only fatal when serve is also absent; the
    // caller decides. Anything else is a degraded scan, not a dead one.
    if (/No OpenCode session store found/.test(err.message)) throw err
    warnThrottled('db', `db scan degraded (${err.message})`)
    return []
  }
}

async function scanThreads() {
  const [serveThreads, dbThreads] = await Promise.all([scanServeSafe(), Promise.resolve().then(scanDBSafe)])
  const byId = new Map()
  for (const t of dbThreads) byId.set(bareId(t.id), t)
  for (const s of serveThreads) {
    const id = bareId(s.id)
    const base = byId.get(id)
    byId.set(id, base ? overlayServe(base, s) : s)
  }
  const merged = [...byId.values()]
  if (!merged.length) {
    throw new Error('No OpenCode session store found (set OPENCODE_DB_PATH or OPENCODE_SERVE_URL)')
  }
  return merged
}

/* ---------------------------------------------------------------- actions */

function openThread(ref) {
  const url = ref && typeof ref.shareUrl === 'string' ? ref.shareUrl.trim() : ''
  if (url && /^https?:\/\//i.test(url)) return { ok: true, url }
  return { ok: false, error: 'That thread is not shared — open it in the OpenCode Desktop app.' }
}

function newSession() {
  return { ok: false, error: 'OpenCode sessions start in the Desktop app or terminal, not from the colony.' }
}

export default {
  id: 'opencode',
  name: 'OpenCode',
  detect,
  scanThreads,
  openThread,
  newSession,
}
