#!/bin/sh
# opencode-tunnel.sh — read-only SSH tunnel to OpenCode Desktop's serve API.
#
# Why this exists: OpenCode Desktop binds its serve API to 127.0.0.1 on a
# RANDOM port with an AUTOGENERATED password, and both rotate on every Desktop
# launch. The colony host therefore cannot point at it directly, and per
# project policy the Desktop must never be disrupted (no restarts, no
# --hostname changes, no firewall rules, no config changes).
#
# What it does, without touching Desktop at all (Desktop never notices):
#   1. resolves the current loopback serve port over SSH (see
#      opencode-resolve.sh — read-only process-env query),
#   2. reads the sidecar's OPENCODE_SERVER_USERNAME/PASSWORD from its own
#      process environment block (values stay in memory),
#   3. opens `ssh -L 127.0.0.1:<local>:127.0.0.1:<remote>` and runs your
#      command with OPENCODE_SERVE_URL / OPENCODE_SERVE_USERNAME /
#      OPENCODE_SERVE_PASSWORD exported. Secrets never touch disk or the repo.
#
# Usage:
#   scripts/opencode-tunnel.sh -- <command...>
#   scripts/opencode-tunnel.sh --print   # detached tunnel + export lines
#                                        # (values visible; prefer exec mode)
#
# Env (required): OPENCODE_SSH_TARGET (e.g. user@winpc-lan),
#                OPENCODE_LOCAL_PORT (default 4096).
#
# Real connection values live in the operator's environment, never in this
# repo (public-fork hygiene: no machine names, LAN IPs, or SSH usernames).
#
# NOTE: never run this script with `sh -x` / `set -x` — traces would leak the
# ephemeral serve password into your shell history / logs.

set -u

TARGET="${OPENCODE_SSH_TARGET:?set OPENCODE_SSH_TARGET=user@winpc-lan (see header)}"
LOCAL_PORT="${OPENCODE_LOCAL_PORT:-4096}"
MODE="exec"

if [ "${1:-}" = "--print" ]; then
  MODE="print"
  shift
fi
if [ "$MODE" = "exec" ] && { [ "${1:-}" != "--" ] || [ $# -lt 2 ]; }; then
  echo "usage: $0 [--print] -- <command...>" >&2
  echo "       $0 --print" >&2
  exit 2
fi
if [ "$MODE" = "exec" ]; then
  shift # drop the --
fi

# --- 1+2. Resolve port + credentials over SSH (read-only probes). ---
HERE="$(dirname "$0")"
PROBE_OUT="$("$HERE/opencode-resolve.sh")" || exit 1

REMOTE_PORT=""
SERVE_USER=""
SERVE_PASS=""
while IFS= read -r line; do
  case "$line" in
    PORT=*) REMOTE_PORT="${line#PORT=}" ;;
    USERNAME=*) SERVE_USER="${line#USERNAME=}" ;;
    PASSWORD=*) SERVE_PASS="${line#PASSWORD=}" ;;
  esac
done <<EOF
$PROBE_OUT
EOF

case "$REMOTE_PORT" in
  '' | *[!0-9]*) echo "opencode-tunnel: no serve port resolved (Desktop restarted? re-run)" >&2; exit 1 ;;
esac
if [ -z "$SERVE_PASS" ]; then
  echo "opencode-tunnel: serve password not found in sidecar env" >&2
  exit 1
fi

# --- 3. Tunnel + command. ---
SERVE_URL="http://127.0.0.1:$LOCAL_PORT"

if [ "$MODE" = "print" ]; then
  ssh -f -N -o ExitOnForwardFailure=yes -o BatchMode=yes \
    -L "127.0.0.1:$LOCAL_PORT:127.0.0.1:$REMOTE_PORT" "$TARGET" </dev/null
  echo "export OPENCODE_SERVE_URL='$SERVE_URL'"
  echo "export OPENCODE_SERVE_USERNAME='$SERVE_USER'"
  echo "export OPENCODE_SERVE_PASSWORD='$SERVE_PASS'"
  echo "# detached tunnel 127.0.0.1:$LOCAL_PORT -> $TARGET:127.0.0.1:$REMOTE_PORT (ephemeral: re-run after any Desktop restart)"
  echo "# to close: pkill -f 'ssh.*-L 127.0.0.1:$LOCAL_PORT:127.0.0.1:'"
  exit 0
fi

ssh -N -o ExitOnForwardFailure=yes -o BatchMode=yes \
  -L "127.0.0.1:$LOCAL_PORT:127.0.0.1:$REMOTE_PORT" "$TARGET" </dev/null &
TUNPID="$!"
trap 'kill "$TUNPID" 2>/dev/null' EXIT INT TERM

tries=0
until curl -s -o /dev/null --max-time 2 "$SERVE_URL/global/health" 2>/dev/null || [ "$tries" -ge 40 ]; do
  tries=$((tries + 1))
  sleep 0.5
done

OPENCODE_SERVE_URL="$SERVE_URL" \
OPENCODE_SERVE_USERNAME="$SERVE_USER" \
OPENCODE_SERVE_PASSWORD="$SERVE_PASS" \
  "$@"
status="$?"
kill "$TUNPID" 2>/dev/null
trap - EXIT INT TERM
exit "$status"
