#!/bin/sh
# opencode-tunnel.sh — read-only SSH tunnel to OpenCode Desktop's serve API.
#
# Why this exists: OpenCode Desktop binds its serve API to 127.0.0.1 on a
# RANDOM port with an AUTOGENERATED password, and both rotate on every Desktop
# launch. The colony host therefore cannot point at it directly, and per
# project policy the Desktop must never be disrupted (no restarts, no
# --hostname changes, no firewall rules, no config changes).
#
# What it does, without touching Desktop at all (Desktop never notices):
#   1. resolves the current loopback serve port over SSH (netstat-level query),
#   2. reads the sidecar's OPENCODE_SERVER_USERNAME/PASSWORD from its own
#      process environment block (read-only OS query, values stay in memory),
#   3. opens `ssh -L 127.0.0.1:<local>:127.0.0.1:<remote>` and runs your
#      command with OPENCODE_SERVE_URL / OPENCODE_SERVE_USERNAME /
#      OPENCODE_SERVE_PASSWORD exported. Secrets never touch disk or the repo.
#
# Usage:
#   scripts/opencode-tunnel.sh -- <command...>
#   scripts/opencode-tunnel.sh --print   # detached tunnel + export lines
#                                        # (values visible; prefer exec mode)
#
# Env overrides: OPENCODE_SSH_TARGET (default user@winpc-lan),
#                OPENCODE_LOCAL_PORT (default 4096).
#
# NOTE: never run this script with `sh -x` / `set -x` — traces would leak the
# ephemeral serve password into your shell history / logs.

set -u

TARGET="${OPENCODE_SSH_TARGET:-user@winpc-lan}"
LOCAL_PORT="${OPENCODE_LOCAL_PORT:-4096}"
MODE="exec"

if [ "${1:-}" = "--print" ]; then
  MODE="print"
  shift
fi
if [ "$MODE" = "exec" ] && { [ "${1:-}" != "--" ] || [ $# -lt 2 ]; }; then
  echo "usage: $0 [--print] -- <command...>" >&2
  echo "       $0 --print" >&2
  exit 2
fi
if [ "$MODE" = "exec" ]; then
  shift # drop the --
fi

# --- 1+2. Resolve port + credentials over SSH (read-only probes). ---
# The PowerShell below walks the sidecar's PEB to read its own environment
# block (PROCESS_QUERY_INFORMATION | PROCESS_VM_READ — purely observational)
# and matches OpenCode-owned loopback listeners to PIDs. Output is three
# `NAME=value` lines; CRs stripped because PowerShell emits CRLF.
PROBE_OUT="$(ssh -o BatchMode=yes -o ConnectTimeout=10 "$TARGET" \
  "powershell -NoProfile -ExecutionPolicy Bypass -Command -" <<'PS_EOF' | tr -d '\r'
Add-Type -TypeDefinition 'using System;using System.Runtime.InteropServices;using System.Text;public class E{[DllImport("kernel32.dll",EntryPoint="OpenProcess")]public static extern IntPtr O(int a,bool b,int c);[DllImport("kernel32.dll",EntryPoint="CloseHandle")]public static extern bool C(IntPtr h);[DllImport("ntdll.dll",EntryPoint="NtQueryInformationProcess")]public static extern int N(IntPtr h,int cl,byte[] pi,int l,ref int r);[DllImport("kernel32.dll",EntryPoint="ReadProcessMemory")]public static extern bool R(IntPtr h,IntPtr a,byte[] b,int s,ref int r);static long P(IntPtr h,long a){byte[] b=new byte[8];int r=0;return R(h,(IntPtr)a,b,8,ref r)?BitConverter.ToInt64(b,0):0;}public static string G(int pid){IntPtr h=O(0x410,false,pid);if(h==IntPtr.Zero)return "OPENFAIL";try{byte[] q=new byte[48];int l=0;if(N(h,0,q,q.Length,ref l)!=0)return "QUERYFAIL";long pb=BitConverter.ToInt64(q,8);long pp=P(h,pb+0x20);if(pp==0)return "NOPEB";long e=P(h,pp+0x80);if(e==0)return "NOENV";StringBuilder s=new StringBuilder();byte[] c=new byte[4096];for(int i=0;i<16;i++){int r=0;if(!R(h,(IntPtr)(e+i*4096),c,4096,ref r))break;s.Append(Encoding.Unicode.GetString(c,0,r));if(s.ToString().Contains((char)0+""+(char)0))break;}return s.ToString();}finally{C(h);}}}';
$ocs=(Get-Process -Name OpenCode -ErrorAction SilentlyContinue).Id;
$conns=Get-NetTCPConnection -State Listen -ErrorAction SilentlyContinue | Where-Object {$ocs -contains $_.OwningProcess -and $_.LocalAddress -eq '127.0.0.1'};
foreach($x in $conns){$raw=[E]::G($x.OwningProcess);$w="";$u="";if($raw -match "OPENCODE_SERVER_PASSWORD=([^`0]*)"){$w=$Matches[1]};if($raw -match "OPENCODE_SERVER_USERNAME=([^`0]*)"){$u=$Matches[1]};if($w.Length -gt 0){Write-Output ("PORT=" + $x.LocalPort);Write-Output ("USERNAME=" + $u);Write-Output ("PASSWORD=" + $w)}}
PS_EOF
)"
if [ -z "$PROBE_OUT" ]; then
  echo "opencode-tunnel: serve probe returned nothing — is OpenCode Desktop running on $TARGET?" >&2
  exit 1
fi

REMOTE_PORT=""
SERVE_USER=""
SERVE_PASS=""
while IFS= read -r line; do
  case "$line" in
    PORT=*) REMOTE_PORT="${line#PORT=}" ;;
    USERNAME=*) SERVE_USER="${line#USERNAME=}" ;;
    PASSWORD=*) SERVE_PASS="${line#PASSWORD=}" ;;
  esac
done <<EOF
$PROBE_OUT
EOF

case "$REMOTE_PORT" in
  '' | *[!0-9]*) echo "opencode-tunnel: no serve port resolved (Desktop restarted? re-run)" >&2; exit 1 ;;
esac
if [ -z "$SERVE_PASS" ]; then
  echo "opencode-tunnel: serve password not found in sidecar env" >&2
  exit 1
fi

# --- 3. Tunnel + command. ---
SERVE_URL="http://127.0.0.1:$LOCAL_PORT"

if [ "$MODE" = "print" ]; then
  ssh -f -N -o ExitOnForwardFailure=yes -o BatchMode=yes \
    -L "127.0.0.1:$LOCAL_PORT:127.0.0.1:$REMOTE_PORT" "$TARGET" </dev/null
  echo "export OPENCODE_SERVE_URL='$SERVE_URL'"
  echo "export OPENCODE_SERVE_USERNAME='$SERVE_USER'"
  echo "export OPENCODE_SERVE_PASSWORD='$SERVE_PASS'"
  echo "# detached tunnel 127.0.0.1:$LOCAL_PORT -> $TARGET:127.0.0.1:$REMOTE_PORT (ephemeral: re-run after any Desktop restart)"
  echo "# to close: pkill -f 'ssh.*-L 127.0.0.1:$LOCAL_PORT:127.0.0.1:'"
  exit 0
fi

ssh -N -o ExitOnForwardFailure=yes -o BatchMode=yes \
  -L "127.0.0.1:$LOCAL_PORT:127.0.0.1:$REMOTE_PORT" "$TARGET" </dev/null &
TUNPID="$!"
trap 'kill "$TUNPID" 2>/dev/null' EXIT INT TERM

tries=0
until curl -s -o /dev/null --max-time 2 "$SERVE_URL/global/health" 2>/dev/null || [ "$tries" -ge 40 ]; do
  tries=$((tries + 1))
  sleep 0.5
done

OPENCODE_SERVE_URL="$SERVE_URL" \
OPENCODE_SERVE_USERNAME="$SERVE_USER" \
OPENCODE_SERVE_PASSWORD="$SERVE_PASS" \
  "$@"
status="$?"
kill "$TUNPID" 2>/dev/null
trap - EXIT INT TERM
exit "$status"
