#!/bin/sh
# opencode-keeper.sh — persistent SSH tunnel to OpenCode Desktop's serve API.
#
# The colony server (bot-crossing.service) reads the live OpenCode threads
# through this keeper: the keeper holds `ssh -L 127.0.0.1:<local>:<remote>`
# open and publishes the CURRENT serve URL + basic-auth credentials to a
# 0600 creds file the adapter reads on every scan. When Desktop restarts
# (random port + autogenerated password both rotate), the keeper re-resolves
# and re-establishes by itself — the colony server never restarts and the
# Desktop is never disrupted (no restarts, no config/firewall changes).
#
# When Desktop/WinPC is unreachable, the keeper removes the creds file so the
# adapter cleanly degrades to zero opencode threads (hermes threads and the
# scan itself are never affected).
#
# Run under systemd (see scripts/systemd/bot-crossing-opencode-keeper.service
# template; the installed unit lives in the operator's ~/.config, never the
# repo). Also safe to run by hand — a lockfile keeps it single-instance.
#
# Env: OPENCODE_SSH_TARGET (required, e.g. user@winpc-lan),
#      OPENCODE_LOCAL_PORT (default 4096),
#      OPENCODE_SERVE_CREDS_FILE (default $XDG_RUNTIME_DIR/bot-crossing/opencode-serve.env,
#                                 else /tmp/bot-crossing/opencode-serve.env),
#      OPENCODE_KEEPER_INTERVAL (probe seconds, default 30).
#
# Real connection values live in the operator's environment, never in this
# repo (public-fork hygiene: no machine names, LAN IPs, or SSH usernames).
#
# NOTE: never run this script with `sh -x` / `set -x` — traces would leak the
# ephemeral serve password into your shell history / logs.

set -u

# Secret files (creds, netrc) are created by this script — deny group/other
# from the start rather than relying on chmod-after-write.
umask 077

TARGET="${OPENCODE_SSH_TARGET:?set OPENCODE_SSH_TARGET=user@winpc-lan (see header)}"
LOCAL_PORT="${OPENCODE_LOCAL_PORT:-4096}"
INTERVAL="${OPENCODE_KEEPER_INTERVAL:-30}"
HERE="$(dirname "$0")"
RESOLVE="$HERE/opencode-resolve.sh"

RUNTIME_DIR="${XDG_RUNTIME_DIR:-/tmp}"
STATE_DIR="$RUNTIME_DIR/bot-crossing"
CREDS_FILE="${OPENCODE_SERVE_CREDS_FILE:-$STATE_DIR/opencode-serve.env}"
LOCK_FILE="$STATE_DIR/opencode-keeper.lock"
NETRC_FILE="$STATE_DIR/.opencode-netrc"

SERVE_URL="http://127.0.0.1:$LOCAL_PORT"

log() {
  # Secrets must never reach the log: callers pass constants only.
  echo "opencode-keeper: $*"
}

# Single instance — systemd is the normal supervisor; this covers hand runs.
mkdir -p "$STATE_DIR"
chmod 700 "$STATE_DIR" 2>/dev/null || true
exec 9>"$LOCK_FILE"
if ! flock -n 9 2>/dev/null; then
  log "another keeper holds $LOCK_FILE — exiting"
  exit 0
fi

TUNPID=""
CUR_PORT=""

tunnel_down() {
  if [ -n "$TUNPID" ]; then
    kill "$TUNPID" 2>/dev/null || true
    TUNPID=""
  fi
  CUR_PORT=""
  rm -f "$CREDS_FILE" "$NETRC_FILE"
}

cleanup() {
  tunnel_down
  log "stopped"
}
# EXIT cleans up after any death; INT/TERM must actually leave (a bare trap
# would run cleanup and then resume the loop, ignoring the signal).
trap cleanup EXIT
trap 'cleanup; exit 0' INT TERM

# Health of the CURRENT tunnel with the GIVEN creds (via a 0600 netrc file
# so the password never appears in a process argument list).
tunnel_healthy() {
  user="$1"
  pass="$2"
  [ -n "$TUNPID" ] || return 1
  kill -0 "$TUNPID" 2>/dev/null || return 1
  printf 'machine 127.0.0.1 login %s password %s\n' "$user" "$pass" >"$NETRC_FILE"
  chmod 600 "$NETRC_FILE"
  code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 3 \
    --netrc-file "$NETRC_FILE" "$SERVE_URL/global/health" 2>/dev/null)"
  [ "$code" = "200" ]
}

write_creds() {
  user="$1"
  pass="$2"
  now_ms="$(date +%s%3N 2>/dev/null || echo $(( $(date +%s) * 1000 )))"
  case "$user$pass" in
    *\'* | *'
'* | *\\*)
      log "resolved credential has an unsafe character — refusing to publish"
      return 1
      ;;
  esac
  tmp="$CREDS_FILE.tmp.$$"
  {
    echo "# generated by opencode-keeper.sh — ephemeral, do not edit"
    echo "OPENCODE_SERVE_URL='$SERVE_URL'"
    echo "OPENCODE_SERVE_USERNAME='$user'"
    echo "OPENCODE_SERVE_PASSWORD='$pass'"
    echo "OPENCODE_SERVE_UPDATED_AT='$now_ms'"
  } >"$tmp"
  chmod 600 "$tmp"
  mv -f "$tmp" "$CREDS_FILE"
}

log "starting (local $SERVE_URL, probe every ${INTERVAL}s)"
while true; do
  if PROBE_OUT="$("$RESOLVE" 2>/dev/null)"; then
    REMOTE_PORT=""
    SERVE_USER=""
    SERVE_PASS=""
    while IFS= read -r line; do
      case "$line" in
        PORT=*) REMOTE_PORT="${line#PORT=}" ;;
        USERNAME=*) SERVE_USER="${line#USERNAME=}" ;;
        PASSWORD=*) SERVE_PASS="${line#PASSWORD=}" ;;
      esac
    done <<EOF
$PROBE_OUT
EOF
    case "$REMOTE_PORT" in
      '' | *[!0-9]*) REMOTE_PORT="" ;;
    esac
    if [ -n "$REMOTE_PORT" ] && [ -n "$SERVE_PASS" ] \
        && { [ "$REMOTE_PORT" != "$CUR_PORT" ] || ! tunnel_healthy "$SERVE_USER" "$SERVE_PASS"; }; then
      # (Re)establish: Desktop restarted, creds rotated, or tunnel died.
      if [ -n "$TUNPID" ]; then
        kill "$TUNPID" 2>/dev/null || true
        TUNPID=""
      fi
      if ssh -N -o ExitOnForwardFailure=yes -o BatchMode=yes \
          -o ServerAliveInterval=15 -o ServerAliveCountMax=3 \
          -L "127.0.0.1:$LOCAL_PORT:127.0.0.1:$REMOTE_PORT" "$TARGET" </dev/null &
      then
        TUNPID="$!"
        tries=0
        until tunnel_healthy "$SERVE_USER" "$SERVE_PASS" || [ "$tries" -ge 10 ]; do
          tries=$((tries + 1))
          sleep 1
        done
        if tunnel_healthy "$SERVE_USER" "$SERVE_PASS"; then
          CUR_PORT="$REMOTE_PORT"
          log "tunnel up (Desktop serve port changed or keeper started)"
        else
          log "tunnel unhealthy after (re)start — will retry"
          tunnel_down
        fi
      else
        log "ssh failed to start — will retry"
        tunnel_down
      fi
    fi
    if [ -n "$CUR_PORT" ] && tunnel_healthy "$SERVE_USER" "$SERVE_PASS" 2>/dev/null; then
      write_creds "$SERVE_USER" "$SERVE_PASS" || tunnel_down
    elif [ -z "$CUR_PORT" ]; then
      : # resolve ok but no tunnel yet — next loop retries; creds stay absent
    fi
  else
    # Desktop/WinPC unreachable — degrade: no creds file, no tunnel.
    if [ -n "$CUR_PORT" ] || [ -e "$CREDS_FILE" ]; then
      log "serve unreachable — withdrawing creds (colony degrades to hermes-only)"
    fi
    tunnel_down
  fi
  # Backgrounded so a trapped signal interrupts the wait at once instead of
  # stalling until the interval ends (systemd stops stay prompt).
  sleep "$INTERVAL" & wait $! 2>/dev/null || true
done
